#!/bin/bash
# SWORBL edge-function deploy — REPO-DRIVEN ENGINE (owner: the game and the
# backend must score with the SAME code). The real engine file is copied in
# as a generated artifact (never hand-edited), then the function deploys.
set -euo pipefail
cd "$(dirname "$0")/../.."
{
  echo "// GENERATED by supabase/functions/deploy.sh — DO NOT EDIT."
  echo "// Source of truth: packages/engine/sworbl-core.js + sworbl-daily.js"
  echo "// (the same modules the app runs). Attaches globalThis.SworblCore"
  echo "// and globalThis.SworblDaily as side effects."
  cat packages/engine/sworbl-core.js
  cat packages/engine/sworbl-daily.js
} > supabase/functions/submit-score/engine-core.js
npx supabase functions deploy submit-score
