#!/bin/bash
# SWORBL edge-function deploy — REPO-DRIVEN ENGINE (owner: the game and the
# backend must score with the SAME code). The real engine file is copied in
# as a generated artifact (never hand-edited), then the function deploys.
set -euo pipefail
cd "$(dirname "$0")/../.."
{
  echo "// GENERATED by supabase/functions/deploy.sh — DO NOT EDIT."
  echo "// Source of truth: packages/engine/sworbl-core.js (the same module"
  echo "// the app runs). Attaches globalThis.SworblCore as a side effect."
  cat packages/engine/sworbl-core.js
} > supabase/functions/submit-score/engine-core.js
npx supabase functions deploy submit-score
